### ISSUE TITLE
About this app

### ISSUE THREAD

**Issue by Team-Creation** [TheSlyProgeny/Icon-Bundler#2]
Dude it honestly sucks.

**Comment by AppleBetas** [comment]
No thanks

**Comment by Team-Creation** [comment]
Oh really? do you even know who the fuck i am?

**Comment by AppleBetas** [comment]
You are Team-Creation.

**Comment by Team-Creation** [comment]
Ha, funny. I'm the reason this whole "Icon Bundler" program even exists...

**Comment by AppleBetas** [comment]
You're Austin, from TeamCreation.

**Comment by Team-Creation** [comment]
I can see what youre saying in slack...

**Comment by AppleBetas** [comment]
O shit waddup

**Comment by Team-Creation** [comment]
Coding lol.

**Comment by AppleBetas** [comment]
Same

**Comment by Team-Creation** [comment]
cool.
